# Generated by Django 2.2.28 on 2023-11-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id_activity', models.TextField(primary_key=True, serialize=False)),
                ('availability', models.TextField()),
            ],
            options={
                'db_table': 'Activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mountaineer',
            fields=[
                ('id_mountaineer', models.TextField(primary_key=True, serialize=False)),
                ('nationality', models.TextField()),
                ('state', models.TextField()),
                ('oxygen', models.TextField()),
            ],
            options={
                'db_table': 'Mountaineer',
                'managed': False,
            },
        ),
    ]
